#!/bin/bash

# This script updates the version number in VERSION.txt and mb_mcp/version.py

# Check if a version number was provided
if [ $# -eq 0 ]; then
    echo "No version number provided. Usage: ./make_version.sh X.Y.Z"
    exit 1
fi

# Update VERSION.txt
echo $1 > VERSION.txt
echo "Updated VERSION.txt to $1"

# Create or update version.py
cat > mb_mcp/version.py << EOL
# This file is automatically generated by make_version.sh
__version__ = "$1"
EOL
echo "Updated mb_mcp/version.py to $1"

# Update __init__.py
sed -i "s/__version__ = .*/__version__ = '$1'/" mb_mcp/__init__.py
echo "Updated mb_mcp/__init__.py to $1"

echo "Version updated to $1"
